// This is automatically generated by CodeBind. Please do not modify it.

public partial class HeadWidget
{
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private UnityEngine.UI.Image m_IconImg;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_NameTMPText;


    public UnityEngine.UI.Image IconImg => m_IconImg;
    public TMPro.TMP_Text NameTMPText => m_NameTMPText;


}
