// This is automatically generated by CodeBind. Please do not modify it.

public partial class TestLoginWindow : CodeBind.ICSCodeBind
{
    public CodeBind.CSCodeBindMono Mono { get; private set; }
    public UnityEngine.Transform Transform { get; private set; }

    public UnityEngine.UI.Button ConfirmBtn { get; private set; }
    public TMPro.TMP_Text TitleTMPText { get; private set; }


    public void InitBind(CodeBind.CSCodeBindMono mono)
    {
        Mono = mono;
        Transform = mono.transform;
        ConfirmBtn = Mono.BindComponents[0] as UnityEngine.UI.Button;
        TitleTMPText = Mono.BindComponents[1] as TMPro.TMP_Text;
    }

    public void ClearBind()
    {
        Mono = null;
        Transform = null;
        ConfirmBtn = null;
        TitleTMPText = null;
    }
}
