// This is automatically generated by CodeBind. Please do not modify it.

public partial class TestLoginForm
{
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private UnityEngine.UI.Button m_ConfirmBtn;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_TipTMPText;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_TitleTMPText;


    public UnityEngine.UI.Button ConfirmBtn => m_ConfirmBtn;
    public TMPro.TMP_Text TipTMPText => m_TipTMPText;
    public TMPro.TMP_Text TitleTMPText => m_TitleTMPText;


}
