// This is automatically generated by CodeBind. Please do not modify it.

using LTools.UI;

public partial class TestLoginWindow
{
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private UnityEngine.UI.Button m_ConfirmBtn;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private BaseWidget m_HeadWidget;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_TipTMPText;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_Tip2TMPText;
    [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
    private TMPro.TMP_Text m_TitleTMPText;


    public UnityEngine.UI.Button ConfirmBtn => m_ConfirmBtn;
    public BaseWidget HeadWidget => m_HeadWidget;
    public TMPro.TMP_Text TipTMPText => m_TipTMPText;
    public TMPro.TMP_Text Tip2TMPText => m_Tip2TMPText;
    public TMPro.TMP_Text TitleTMPText => m_TitleTMPText;


}
